### ISSUE TITLE
如何支持’获取展示后广告信息事例‘

### ISSUE THREAD

**Issue by J-Yaleen** [50431040/flutter_gromore#12]
描述
穿山甲有个获取展示后广告信息事例的方法
希望支持这个方法（getShowEcpmInfo），或者有什么临时的方法吗？
![image](https://github.com/50431040/flutter_gromore/assets/107242550/fa4d08e6-f4d4-47a7-9dca-925de9f06e38)

**Comment by 50431040** [comment]
你是想要广告的广告商、广告位ID吗？

**Comment by J-Yaleen** [comment]
我想要这些信息
![image](https://github.com/50431040/flutter_gromore/assets/107242550/a306c680-e534-47ef-bfdb-f22874f46b60)

**Comment by 50431040** [comment]
可以支持。
