### ISSUE TITLE
首次打开APP无法展示开屏广告问题

### ISSUE THREAD

**Issue by jimtan2015** [50431040/flutter_gromore#13]
大佬您好，使用该插件会出现首次打开APP无法展示开屏的问题，具体表现如下：
1、首次打开APP冷启动时，无法展示开屏广告；
2、需要退出APP，二次打开APP后才能显示开屏广告，此举可能浪费流量。
官方文档描述如下：
https://www.csjplatform.com/supportcenter/5885
能否在插件层面进行支持呢？感谢您

**Comment by 50431040** [comment]
若需要添加本地缓存配置，请将文件gromore_local_config放在android/src/main/assets/目录下，初始化时会尝试加载该文件配置。文档中有说明
