### ISSUE TITLE
老哥可以升级一下gradle版本吗，7.3.x以上，谢谢

### ISSUE THREAD

**Issue by propertyabc** [50431040/flutter_gromore#15]
安卓报错信息：
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_gromore' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

我的配置：
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

**Comment by 50431040** [comment]
方便降级吗？com.android.tools.build:gradle:7.1.2 即可

**Comment by propertyabc** [comment]
好的好的 7.1.2可以的，感谢解答🙏！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月21日 16:20 |
| 收件人 | 50431040/flutter_gromore ***@***.***> |
| 抄送人 | what ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [50431040/flutter_gromore] 老哥可以升级一下gradle版本吗，7.3.x以上，谢谢 (Issue #15) |

方便降级吗？com.android.tools.build:gradle:7.1.2 即可
