### ISSUE TITLE
GromoreFeedView 在一个信息流页面，每隔10个元素展示一次广告；但是只有第一个成功展示，其他都是白屏，这种情况怎么解决哈，感谢

### ISSUE THREAD

**Issue by propertyabc** [50431040/flutter_gromore#17]
GromoreFeedView 在一个信息流页面，每隔10个元素展示一次广告；但是只有第一个成功展示，其他都是白屏，这种情况怎么解决哈，感谢

**Comment by 50431040** [comment]
看下feedId是否传的相同的值，feedId需要先获取，再展示

**Comment by propertyabc** [comment]
> 看下feedId是否传的相同的值，feedId需要先获取，再展示

使用了demo里面提供的FeedView，可以了； 不过貌似存在广告区域白屏问题，轻轻滑动一下页面 广告就会展示，后面确认了我再提问题

感谢老哥，成功接入了，谢谢谢谢🙏🙏
