### ISSUE TITLE
宿主包，引入其他ADN报错

### ISSUE THREAD

**Issue by propertyabc** [50431040/flutter_gromore#19]
<img width="1286" alt="image" src="https://github.com/50431040/flutter_gromore/assets/7914324/485bce39-1489-4392-a3d1-1233438e170a">

**Comment by 50431040** [comment]
用aar的方式的话需要下载文件下来放对应目录，GDTSDK和Baidu_MobAds_SDK

**Comment by propertyabc** [comment]
好的好的，这样可以了，感谢感谢 小白了我
------------------

    implementation "com.pangle.cn:mediation-ks-adapter:3.3.55.2.1"//ks adapter
    implementation "com.pangle.cn:mediation-gdt-adapter:4.550.1420.2" //gdt adapter
    implementation "com.pangle.cn:mediation-baidu-adapter:9.324.0"//baidu adapter
