### ISSUE TITLE
ks gdt baidu实际接入失败了，麻烦帮忙看一下原因吧谢谢🙏

### ISSUE THREAD

**Issue by propertyabc** [50431040/flutter_gromore#20]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.msdk.adapter.ks.KsAdapterConfiguration"

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.msdk.adapter.gdt.GdtSplashLoader"

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.msdk.adapter.baidu.BaiduSplashLoader"

<img width="600" alt="image" src="https://github.com/50431040/flutter_gromore/assets/7914324/09a8125c-c0fd-4970-acb0-de362d599286">
<img width="327" alt="image" src="https://github.com/50431040/flutter_gromore/assets/7914324/95991835-286c-40c3-96bd-3ce04abf0be6">

I/TTMediationSDK_SDK_Init(22325): ------------------ 聚合 接入信息 start ---------------------
D/TTMediationSDK_SDK_Init(22325): 当前接入的聚合 SDK版本是：5.5.1.5
D/AdvertisingIdHelper(22325): mGAId: , get gaid consume time :4
I/TTMediationSDK_SDK_Init(22325): 已按要求接入三方广告sdk【gdt】
I/TTMediationSDK_SDK_Init(22325): 已按要求接入三方广告sdk【ks】
I/TTMediationSDK_SDK_Init(22325): 已按要求接入三方广告sdk【baidu】
I/TTMediationSDK_SDK_Init(22325): 已按要求接入三方广告sdk【pangle】
I/TTMediationSDK_SDK_Init(22325): ------------------ GroMore 接入信息 end ---------------------
I/TTMediationSDK_SDK_Init(22325): ------------------ GroMore 版本信息 start ---------------------
E/TTMediationSDK_SDK_Init(22325): gdt版本号： , ***gdtAdapter未接入，请检查***, 聚合版本不符合，要求等于.x ，当前是5.5.1.5
E/TTMediationSDK_SDK_Init(22325): ks版本号： , ***ksAdapter未接入，请检查***, 聚合版本不符合，要求等于.x ，当前是5.5.1.5
E/TTMediationSDK_SDK_Init(22325): baidu版本号： , ***baiduAdapter未接入，请检查***, 聚合版本不符合，要求等于.x ，当前是5.5.1.5
I/TTMediationSDK_SDK_Init(22325): ------------------ GroMore 版本信息 end ---------------------
I/TTMediationSDK_SDK_Init(22325): ------------------ GroMore 支持ADN初始化信息 start ---------------------
I/TTMediationSDK_SDK_Init(22325): adnName = pangle 初始化成功
I/TTMediationSDK_SDK_Init(22325): ------------------ GroMore 支持ADN初始化信息 end ---------------------

看起来实际上只初始化成功了 pangle的

**Comment by anandzhang** [comment]
@50431040 cc

**Comment by 50431040** [comment]
应该是版本问题，用demo里面的SDK和适配器版本试试

**Comment by propertyabc** [comment]
> 应该是版本问题，用demo里面的SDK和适配器版本试试

就是直接copy的demo里面的配置，所以比较纳闷～
<img width="1226" alt="image" src="https://github.com/50431040/flutter_gromore/assets/7914324/219013a4-f962-4fc5-9a69-760ce13d6001">

**Comment by propertyabc** [comment]
https://www.csjplatform.com/union/media/union/download/detail?id=142&docId=27562&osType=android
  
这一块尝试配置了，但是有报错
`
mediationAutoAdapter {
    //自动适配adn 所有adn adapter，默认值为true，如果为false脚本功能全部关闭
    autoUpdate true 
    //如果不想全部自动适配，可选择此项，默认值为空[]，可以不填写
    //如果autoUpdate设置成false，此项不生效，不会自动适配adn adapter
    //如果autoUpdate设置成true，autoUpdateAdn配置了adn，则生效配置的adn。
    //autoUpdateAdn没有配置adn，自动适配所有的adn
    autoUpdateAdn = ["gdt","baidu","ks"] 
`

**Comment by 50431040** [comment]
gromore上面配置了这几个平台吗？

**Comment by propertyabc** [comment]
> gromore上面配置了这几个平台吗？

没有没有，app还没上线，直接用的你们的小牛招聘的公告ID配置的

**Comment by 50431040** [comment]
那你直接clone下来，运行demo就行了
