### ISSUE TITLE
广告初始化冲突

### ISSUE THREAD

**Issue by CatEatFishs** [50431040/flutter_gromore#21]
背景：Flutter项目的android目录下集成了穿山甲的短剧SDK，但是短剧sdk初始化前需要先初始化广告sdk。广告sdk+短剧sdk初始化完成后再初始化fltter_grome插件，插件初始化就失败，没有具体错误原因。
问题：猜测android下的广告sdk初始化后，插件就不会再初始化了。
请问如何解决这个初始化冲突问题？穿山甲客服没有提供解决方案。

**Comment by 50431040** [comment]
看了一下短剧SDK的集成文档，两者好像并没有关联

**Comment by 50431040** [comment]
文档说的是：在穿山甲广告 SDK 初始化成功的回调中启动短剧 SDK。
应该是先初始化短剧SDK，然后初始化gromore，最后通过 DJXSdk.start 启动短剧服务

**Comment by CatEatFishs** [comment]
非常感谢你的回复。
![image](https://github.com/50431040/flutter_gromore/assets/24956075/d8fea48b-0a56-4d09-a9c8-827253b5cc21)
先初始化短剧SDK会有这个报错提示。必须先初始化穿山甲广告SDK才可以。
我现在的流程是，先初始化穿山甲广告SDK，拿到成功回调后再初始化短剧SDK，gromore与穿山甲广告SDK是异步执行的。这个流程是有冲突报错的。流程如图。
<img width="807" alt="image" src="https://github.com/50431040/flutter_gromore/assets/24956075/6d839b43-2f9c-418e-af0c-c769ae21b8a2">

你说的这个流程【应该是先初始化短剧SDK，然后初始化gromore，最后通过 DJXSdk.start 启动短剧服务】必须要同步执行吗？我试试这个同步流程。

**Comment by 50431040** [comment]
嗯是需要同步执行的

**Comment by CatEatFishs** [comment]
你好，我已经同步执行了，流程是初始化广告SDK，成功回调后初始化短剧sdk，然后初始化groMore ，groMore初始化FlutterGromore.initSDK(),返回true 后，再启动短剧服务，流程代码图如下：
<img width="1156" alt="image" src="https://github.com/50431040/flutter_gromore/assets/24956075/2a77cb00-efd5-4daa-a129-b50ac8ebcf44">
这样的结果是短剧能正常运行，但是gromore没有初始化成功，bool result = await FlutterGromore.initSDK(),这个result是 true，但是在调用gromore广告时会报错，如下图
<img width="1650" alt="image" src="https://github.com/50431040/flutter_gromore/assets/24956075/6746367a-542b-41f6-bbbf-1e38bfd6fdba">
请问遇到这种情况我应该怎么处理呢？期待你的回复。

**Comment by CatEatFishs** [comment]
groMore初始化打印日志，并没有明显的错误日志，如图
<img width="1521" alt="image" src="https://github.com/50431040/flutter_gromore/assets/24956075/e2aab78d-9793-497a-889e-d2861fb0a4ad">

**Comment by 50431040** [comment]
初始化成功的话是有日志的，看下demo能正常初始化吗

**Comment by CatEatFishs** [comment]
> 初始化成功的话是有日志的，看下demo能正常初始化吗

如果不初广告sdk，gromore就能初始化成功，广告sdk 跟 gromore 还是有冲突，单独初始化一个都没问题。

**Comment by 50431040** [comment]
README 添加了群二维码

**Comment by 50431040** [comment]
我看提供的短剧demok里面用的广告SDK版本很低，你用flutter_gromore 1.0.11 版本的试下，文档 https://github.com/50431040/flutter_gromore/blob/main/v1.x_README.md

**Comment by nnianhouss** [comment]
> README 添加了群二维码

二维码失效了 如何加群

**Comment by 50431040** [comment]
> > README 添加了群二维码
> 
> 二维码失效了 如何加群

![IMG_5750](https://github.com/50431040/flutter_gromore/assets/30379566/f36771d7-9313-473b-a72e-fb3a3a9ea72d)
