### ISSUE TITLE
onSplashAdLoadFail 无错误信息

### ISSUE THREAD

**Issue by JiLongQiu** [50431040/flutter_gromore#22]
加载开屏广告的时候，onSplashAdLoadFail，但没有任何的提示信息，这种情况该怎么来排查呢

await FlutterGromore.showSplashAd(
config: GromoreSplashConfig(
    adUnitId: "xxxxxx广告位ID"),
callback: GromoreSplashCallback(() {
  print("callback --- onAdEnd");
}));

flutter: {name: onSplashAdLoadFail, id: 813803035}
flutter: {name: onAdEnd, id: 813803035}
flutter: callback --- onAdEnd

**Comment by 50431040** [comment]
运行下Demo看看正常吗
