### ISSUE TITLE
麻烦帮忙看下吧，谢谢 (40005, reason: 0  message: 广告位尺寸不能为空, reason: 0  message: 广告位尺寸不能为空, null) 

### ISSUE THREAD

**Issue by kingrmb** [50431040/flutter_gromore#23]
<img width="1028" alt="image" src="https://github.com/50431040/flutter_gromore/assets/124293662/65ab444f-a1f2-4697-8a02-208bc4f07220">

**Comment by kingrmb** [comment]
@50431040  辛苦帮忙看下，谢谢；加了宽高也有报错

**Comment by 50431040** [comment]
width和height目前没有用到，请提供完整的版本信息：插件版本、广告sdk版本、适配器版本

**Comment by kingrmb** [comment]
> width和height目前没有用到，请提供完整的版本信息：插件版本、广告sdk版本、适配器版本
@50431040  辛苦
flutter_gromore: ^2.0.10

    // 优量汇 = 广点通
    implementation(name: 'GDTSDK.unionNormal.4.540.1410', ext: 'aar')
    implementation "com.pangle.cn:mediation-gdt-adapter:4.540.1410.1"

    // 百度
    implementation(name: 'Baidu_MobAds_SDK_v9.313', ext: 'aar')
    implementation "com.pangle.cn:mediation-baidu-adapter:9.313.1"

    // 快手
    implementation(name: 'kssdk-ad-3.3.51.1', ext: 'aar')
    implementation "com.pangle.cn:mediation-ks-adapter:3.3.51.1.0"

**Comment by 50431040** [comment]
Android是吧？

**Comment by 50431040** [comment]
你这个是信息流广告的日志吗？

**Comment by kingrmb** [comment]
嗯 安卓的，开屏广告的报错；刚试了信息流也报这个错误

**Comment by 50431040** [comment]
可以的话在Readme加下我好友

**Comment by kingrmb** [comment]
好 刚才找了半天没看到，马上，感谢感谢

**Comment by kingrmb** [comment]
@50431040

**Comment by kingrmb** [comment]
加了加了
