### ISSUE TITLE
iOS编译报错 No such module 'BUAdSDK'

### ISSUE THREAD

**Issue by Ymmmsick** [50431040/flutter_gromore#24]
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): No such module 'BUAdSDK'
/Users/ymmmsick/Dev/StudioProjects/xFluttter/flutter_gromore/ios/Classes/view/FlutterGromoreBanner.swift:8:7

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

您好用的demo编译出现了这个报错，可能是什么原因造成的呢
pod里面看大有BUAdSDK
<img width="267" alt="image" src="https://github.com/50431040/flutter_gromore/assets/5235312/1f5d6bd3-2243-495f-8095-0affb563472f">

**Comment by 50431040** [comment]
1. Quit xcode
2. Run "pod update" in terminal
3. Open .xcworkspace and build again.
