### ISSUE TITLE
信息流广告获取id失败, 渲染方式为模版渲染

### ISSUE THREAD

**Issue by bianweiall** [50431040/flutter_gromore#25]
![xxx](https://github.com/50431040/flutter_gromore/assets/3282768/726416e9-48ba-4e4c-90b1-47ae8ff2d175)

**Comment by 50431040** [comment]
![image](https://github.com/50431040/flutter_gromore/assets/30379566/46b929f6-400f-4f26-aea3-390ae6c7f1b8)
这个是非模板吧

**Comment by bianweiall** [comment]
是模板渲染的，选择了一个左图右文的模板

**Comment by 50431040** [comment]
> 是模板渲染的，选择了一个左图右文的模板

看下我截图的那个代码位配置
