### ISSUE TITLE
信息流广告滑动遮盖其他控件

### ISSUE THREAD

**Issue by moujunqiang** [50431040/flutter_gromore#9]
![251034cec26269cb6557a20d40db33f](https://github.com/50431040/flutter_gromore/assets/22389682/5229a2d8-a073-46fc-9e5a-51bab973e1cd)
信息流广告滑动得时候直接把底部按钮和顶部标题栏都遮挡住了，这种情况正常吗

**Comment by 50431040** [comment]
检查一下布局呢，目前没有发现此问题

**Comment by moujunqiang** [comment]
上面是我直接用demo中测试效果 麻烦您看一下呢

**Comment by moujunqiang** [comment]
布局什么都没有改变，只是改变了广告位id

**Comment by 50431040** [comment]
> 

应该和素材有关系，我这边测试的是图文素材（左图右文）
